// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5-fVAJfWOSjAMjXrJGJfHqNeCc4iU20',
    appId: '1:728675062371:web:f680ae1a9718904380de56',
    messagingSenderId: '728675062371',
    projectId: 'carmark-498fa',
    authDomain: 'carmark-498fa.firebaseapp.com',
    storageBucket: 'carmark-498fa.appspot.com',
    measurementId: 'G-PWPSQCR493',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3bMdKAh4X5zF8FxkE83IikeqbZ9-P-Y',
    appId: '1:728675062371:android:9743b04078ad0efd80de56',
    messagingSenderId: '728675062371',
    projectId: 'carmark-498fa',
    storageBucket: 'carmark-498fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFfsqyo55DpGnqhLmEORESnm7McE-Stik',
    appId: '1:728675062371:ios:b296f46064f0097f80de56',
    messagingSenderId: '728675062371',
    projectId: 'carmark-498fa',
    storageBucket: 'carmark-498fa.appspot.com',
    iosBundleId: 'com.carmark.carmark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFfsqyo55DpGnqhLmEORESnm7McE-Stik',
    appId: '1:728675062371:ios:b296f46064f0097f80de56',
    messagingSenderId: '728675062371',
    projectId: 'carmark-498fa',
    storageBucket: 'carmark-498fa.appspot.com',
    iosBundleId: 'com.carmark.carmark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv5-fVAJfWOSjAMjXrJGJfHqNeCc4iU20',
    appId: '1:728675062371:web:be8a936c7ca97d8e80de56',
    messagingSenderId: '728675062371',
    projectId: 'carmark-498fa',
    authDomain: 'carmark-498fa.firebaseapp.com',
    storageBucket: 'carmark-498fa.appspot.com',
    measurementId: 'G-3XDKHGPEWV',
  );
}
